# 30th November 2019

In [1]:
import numpy as np

# OPERATIONS ON NEW ARRAY

In [2]:
array6=np.array([[10,30,10],[60,5,9]])
array7=np.array([[20,5,40],[50,43,20]])

In [3]:
np.add(array6,array7)

array([[ 30,  35,  50],
       [110,  48,  29]])

In [4]:
np.subtract(array6,array7)#  is equal to array6-array7

array([[-10,  25, -30],
       [ 10, -38, -11]])

In [5]:
array6-array7

array([[-10,  25, -30],
       [ 10, -38, -11]])

In [6]:
np.multiply(array6,array7) # it is same as array6*array7

array([[ 200,  150,  400],
       [3000,  215,  180]])

In [7]:
array6*array7

array([[ 200,  150,  400],
       [3000,  215,  180]])

In [8]:
print(array6,array7)
np.divide(array6,array7)

[[10 30 10]
 [60  5  9]] [[20  5 40]
 [50 43 20]]


array([[0.5       , 6.        , 0.25      ],
       [1.2       , 0.11627907, 0.45      ]])

In [9]:
print(array6)
np.square(array6)

[[10 30 10]
 [60  5  9]]


array([[ 100,  900,  100],
       [3600,   25,   81]])

In [10]:
array6*array6

array([[ 100,  900,  100],
       [3600,   25,   81]])

In [11]:
np.sqrt(array6)

array([[3.16227766, 5.47722558, 3.16227766],
       [7.74596669, 2.23606798, 3.        ]])

In [12]:
# print(array6)
np.exp(array6)# e to the power n(element of the array)

array([[2.20264658e+04, 1.06864746e+13, 2.20264658e+04],
       [1.14200739e+26, 1.48413159e+02, 8.10308393e+03]])

# sigmoid function

In [13]:
p=1/(1+np.exp(-array6)) # it is use in sigmoid function i.e probability
p

array([[0.9999546 , 1.        , 0.9999546 ],
       [1.        , 0.99330715, 0.99987661]])

In [14]:
np.power(array6,2)

array([[ 100,  900,  100],
       [3600,   25,   81]])

In [15]:
array6==array7 # it will compare element wise

array([[False, False, False],
       [False, False, False]])

In [16]:
array6<array7

array([[ True, False,  True],
       [False,  True,  True]])

In [17]:
array8=np.array([1,2,3,4])
array9=np.array([1,2,3,4])
array10=np.array([5,3,4,5])

In [18]:
np.array_equal(array8,array10)

False

In [19]:
array6

array([[10, 30, 10],
       [60,  5,  9]])

In [20]:
array6.sum()

124

In [21]:
np.sum(array6)

124

In [22]:
np.mean(array6) # to find mean

20.666666666666668

In [23]:
np.sum(array6)/array6.size# to find mean manually

20.666666666666668

In [24]:
print(array6)
np.mean(array6,axis=0)

[[10 30 10]
 [60  5  9]]


array([35. , 17.5,  9.5])

In [25]:
np.mean(array6,axis=1)

array([16.66666667, 24.66666667])

In [26]:
np.sort(array6.flatten()) #  it sorts the elements row wise

array([ 5,  9, 10, 10, 30, 60])

In [27]:
# median
np.median(array6)

10.0

In [28]:
np.sort(array6)

array([[10, 10, 30],
       [ 5,  9, 60]])

In [29]:
print(array6)
np.median(array6,axis=0)

[[10 30 10]
 [60  5  9]]


array([35. , 17.5,  9.5])

In [30]:
np.median(array6,axis=1)

array([10.,  9.])

In [31]:
print(array6)
np.sum(array6,axis=0)

[[10 30 10]
 [60  5  9]]


array([70, 35, 19])

In [32]:
np.sum(array6,axis=1)

array([50, 74])

In [33]:
np.max(array6) # max. elements of the array

60

In [34]:
print(array6)
np.max(array6,axis=0)

[[10 30 10]
 [60  5  9]]


array([60, 30, 10])

In [35]:
np.max(array6,axis=1)

array([30, 60])

In [36]:
# softmax function = e to power x upon sigma e to the power x
np.exp(array6)/np.sum(np.exp(array6))

array([[1.92874985e-22, 9.35762297e-14, 1.92874985e-22],
       [1.00000000e+00, 1.29958143e-24, 7.09547416e-23]])

In [37]:
np.min(array6)

5

In [38]:
print(array6)
np.min(array6,axis=0)

[[10 30 10]
 [60  5  9]]


array([10,  5,  9])

In [39]:
np.argmin(array6)#Indices of the minimum elements of a N-dimensional array:

4

In [40]:
np.argmax(array6)#Indices of the maximum elements of a N-dimensional array:

3

In [41]:
array6.flatten()

array([10, 30, 10, 60,  5,  9])

In [42]:
array6.argmax()

3

In [43]:
np.cumsum(array6)# cumsum()==cumulative frequecy

array([ 10,  40,  50, 110, 115, 124])

In [44]:
print(f'array6 before transpose\n {array6}')
array6.T# here T stands for tranpose(row ------------------> column)

array6 before transpose
 [[10 30 10]
 [60  5  9]]


array([[10, 60],
       [30,  5],
       [10,  9]])

In [45]:
np.dot(array6,array7.T)# clear the concept of dot product in matrix

array([[ 750, 1990],
       [1585, 3395]])

In [46]:
array6.shape,(array6.T).shape

((2, 3), (3, 2))

In [47]:
np.cross(array6,array6)# hide and the row and column and then multiply

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
#   RESHAPE(no of factors of the total no. elements of the array) THE ARRAY

In [49]:
array6

array([[10, 30, 10],
       [60,  5,  9]])

In [50]:
array6.reshape(1,6)

array([[10, 30, 10, 60,  5,  9]])

In [51]:
array6.reshape(3,2)

array([[10, 30],
       [10, 60],
       [ 5,  9]])

In [52]:
array6.reshape(-1,6)# here -1 means any no. of rows but 6 denotes no. of columns

array([[10, 30, 10, 60,  5,  9]])

In [53]:
array6.reshape(6,-1)# here -1 means any no. of columns but 6 denotes no. of rows

array([[10],
       [30],
       [10],
       [60],
       [ 5],
       [ 9]])

# cancatenation of the array

In [54]:
array6,array7

(array([[10, 30, 10],
        [60,  5,  9]]), array([[20,  5, 40],
        [50, 43, 20]]))

In [55]:
# In this no. of rows increases
np.vstack((array6,array7))# It is used to stack arrays in sequence vertically (row wise)

array([[10, 30, 10],
       [60,  5,  9],
       [20,  5, 40],
       [50, 43, 20]])

In [56]:
# In this no. of columns increases
np.hstack((array6,array7))

array([[10, 30, 10, 20,  5, 40],
       [60,  5,  9, 50, 43, 20]])

In [57]:
# Another way of concatenation
np.concatenate((array6,array7))# here you can also give axis

array([[10, 30, 10],
       [60,  5,  9],
       [20,  5, 40],
       [50, 43, 20]])

# Boolean indexing

In [58]:
array6%10==0 # this whole thing is also used as index when passed in any array,see below

array([[ True,  True,  True],
       [ True, False, False]])

In [59]:
array6%10 # it is returning the modulus remainder after dividing 

array([[0, 0, 0],
       [0, 5, 9]])

In [60]:
array6[array6%10==0]

array([10, 30, 10, 60])

In [61]:
print(array6)
array6[array6%10==0]+=300
array6

[[10 30 10]
 [60  5  9]]


array([[310, 330, 310],
       [360,   5,   9]])

In [72]:
array6[(array6%11==0) & (array6%5==0)]# here & is working like and like python 
# but you can't use here and

array([330])

In [63]:
np.where(array6>=110)# return index of the elements which satisfy condition

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

In [80]:
array8=np.array([1,1,3,5,4,6,5,4])

In [81]:
np.unique(array8) # It returns unique elements of array sorting ascending order 

array([1, 3, 4, 5, 6])

In [82]:
np.unique(array8,return_counts=True)# returns the count of the unique elements

(array([1, 3, 4, 5, 6]), array([2, 1, 2, 2, 1]))

In [67]:
np.unique(array8,return_index=True)# returns the first occurance the unuque elements 

(array([1, 3, 4, 5, 6]), array([0, 2, 4, 3, 5]))

In [68]:
np.unique(array8,return_index=True)

(array([1, 3, 4, 5, 6]), array([0, 2, 4, 3, 5]))

In [69]:
# broadcasting  (it  multiply the two matrix forcefully)
# its a advance feature of numpy