## 16th,February 2020

In [1]:
import numpy as np

## comparison b/w list and numpy

In [2]:
import sys
list_arr=range(10000)
print(sys.getsizeof(list_arr))
print(sys.getsizeof(60)*10000)

48
280000


In [3]:
numpy_arr=np.arange(10000)
print(numpy_arr.itemsize*numpy_arr.size)

80000


In [4]:
%timeit [i**2 for i in list_arr]

2.41 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit numpy_arr**2

3.74 µs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 1-D Array Vector

In [6]:
#Cordinates of a point , x=10,y=12,z=50
cordinates=[10,12,50]
arr0=np.array(cordinates)

In [7]:
arr0

array([10, 12, 50])

In [8]:
type(arr0)

numpy.ndarray

In [9]:
arr0.ndim# Rank 1 order of array

1

In [10]:
arr0.shape#(no. of rows,no. of columns)

(3,)

In [11]:
arr0.size

3

In [12]:
arr0.dtype# It gives the type of each elements

dtype('int64')

In [13]:
weather=[[5,15,35],[9,25,30],[4,17,45]]
arr1=np.array(weather)
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [14]:
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)

<class 'numpy.ndarray'>
(3, 3)
2
int64


## Home Work ,See the 3-Dimention  data storing

In [15]:
arr0.size

3

In [16]:
arr1.size

9

In [17]:
arr1.itemsize
arr1.itemsize

8

In [18]:
arr1.nbytes

72

#  numpy Built-in Functions

In [19]:
# np.arange(start(otional):stop(exclusive):step(otional,step may int or float))

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [22]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
np.arange(10,30,.2)

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4,
       16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6,
       18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6, 20.8,
       21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8, 23. ,
       23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. , 25.2,
       25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2, 27.4,
       27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4, 29.6,
       29.8])

In [24]:
# np.linspace(start(inclusive),stop(inclusive),total no. of divisions)
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [25]:
np.linspace(10,15,5,endpoint=False)

array([10., 11., 12., 13., 14.])

In [26]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [27]:
np.around(np.linspace(1,2,10),2)

array([1.  , 1.11, 1.22, 1.33, 1.44, 1.56, 1.67, 1.78, 1.89, 2.  ])

In [28]:
np.zeros((2,3))#Null matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.identity(4)#Identity matrix,leading diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
np.diag((3,6,7))

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 7]])

In [33]:
np.diag(arr1)

array([ 5, 25, 45])

In [34]:
np.triu((2,3))#upper matrix

array([[2, 3],
       [0, 3]])

## Uniform Distribution

In [35]:
np.random.rand(2,4)#Uniform distribution <-------------------------------
                   #It takes the tuple i.e 2,4
                   #Create an array of the given shape and populate it with
                   #random samples from a uniform distribution over ``[0, 1)``.

array([[0.13382861, 0.68317978, 0.4981909 , 0.63094382],
       [0.97663167, 0.50947539, 0.70192129, 0.30052004]])

## Standard Normal Distribution

In [36]:
np.random.randn(2,3)#Normal distribution <------------------------------------
                    #Return a sample (or samples) from the "standard normal" 
                    #distribution.


array([[-1.88681672,  1.39173916,  0.44353933],
       [-0.1699275 , -0.91137592,  0.84712135]])

In [37]:
np.random.random((2,3))

array([[0.36453284, 0.02086787, 0.08289548],
       [0.07950942, 0.16969731, 0.72684053]])

In [38]:
np.random.randint((4,30,5))# Here 5 is the shape

array([0, 2, 0])

## Discreate Uniform distribution

In [39]:
np.random.randint(4,30,(3,2))

array([[17,  4],
       [21, 19],
       [29, 26]])

In [40]:
np.random.seed(0)#This is a convenience, legacy function.,here inside seed() value anything like 0,1,2,3...
np.random.randint(4,30,(3,2))

array([[16, 19],
       [25,  4],
       [ 7,  7]])

In [41]:
np.random.seed(0)
np.random.randint(4,30,(2,3))

array([[16, 19, 25],
       [ 4,  7,  7]])

## Accessing of Elements

## Indexing

In [42]:
arr0

array([10, 12, 50])

In [43]:
arr0[2]

50

In [44]:
arr0[-1]

50

In [45]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [46]:
arr1[2][1]

17

In [47]:
arr1[-2,-1]

30

## Index Slicing

In [48]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [49]:
# arr1[start,stop,step]# all thin optional
arr1[::]

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [50]:
arr1[::2]

array([[ 5, 15, 35],
       [ 4, 17, 45]])

In [51]:
x=arr0[1::]
x

array([12, 50])

In [52]:
x[0]

12

In [53]:
x[0]=17

In [54]:
arr0

array([10, 17, 50])

## Home Work ,See the 3-Dimention  data storing1

## 22nd,February 2020

In [55]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [56]:
arr1[1]

array([ 9, 25, 30])

In [57]:
arr1[1][2]

30

In [58]:
arr1[[1,2],[2,1]]

array([30, 17])

In [59]:
arr1[1:,1:]

array([[25, 30],
       [17, 45]])

In [60]:
arr1[::2,::2]

array([[ 5, 35],
       [ 4, 45]])

In [61]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 45]])

In [62]:
arr1[-1:-3:-1,-2::-1]

array([[17,  4],
       [25,  9]])

## Filtering

In [63]:
# Filtering means condition based data
arr1%5==0

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [64]:
arr1[arr1%5==0]

array([ 5, 15, 35, 25, 30, 45])

In [65]:
arr1[arr1%5==0]*=5

In [66]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [67]:
#multiple condition
arr1[(arr1%5==0) & (arr1%2==0)]

array([150])

## To know the index

In [68]:
arr1[arr1%5==0]

array([ 25,  75, 175, 125, 150, 225])

In [69]:
np.where(arr1%5==0)#To know the index of the given condition

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))

In [70]:
np.argwhere(arr1%5==0)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 2]])

In [71]:
np.argwhere(arr1%5==0)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 2]])

## Array MOdification

In [72]:
arr0

array([10, 17, 50])

In [73]:
np.append(arr0,50)#changing is not done originally

array([10, 17, 50, 50])

In [74]:
np.append(arr0,[5,19])#appending multiple elements

array([10, 17, 50,  5, 19])

In [75]:
arr0#Not changed yet

array([10, 17, 50])

In [76]:
np.insert(arr0,1,34)

array([10, 34, 17, 50])

In [77]:
np.insert(arr0,1,[34,45])

array([10, 34, 45, 17, 50])

In [78]:
np.insert(arr0,[0,2],[34,45])

array([34, 10, 17, 45, 50])

## 2-D Array

In [79]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [80]:
np.append(arr1,[5,55,65])

array([ 25,  75, 175,   9, 125, 150,   4,  17, 225,   5,  55,  65])

In [81]:
np.append(arr1,[[5,55,65]],axis=0)

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225],
       [  5,  55,  65]])

In [82]:
np.append(arr1,[[5],[55],[65]],axis=1)

array([[ 25,  75, 175,   5],
       [  9, 125, 150,  55],
       [  4,  17, 225,  65]])

In [83]:
np.append(arr1,[[5,6],[55,65],[65,75]],axis=1)

array([[ 25,  75, 175,   5,   6],
       [  9, 125, 150,  55,  65],
       [  4,  17, 225,  65,  75]])

In [84]:
np.insert(arr1,1,[5,55,65],axis=0)#insserting value in row

array([[ 25,  75, 175],
       [  5,  55,  65],
       [  9, 125, 150],
       [  4,  17, 225]])

In [85]:
np.insert(arr1,1,[[5,55,65],[7,87,97]],axis=0)

array([[ 25,  75, 175],
       [  5,  55,  65],
       [  7,  87,  97],
       [  9, 125, 150],
       [  4,  17, 225]])

In [86]:
np.insert(arr1,[1,3],[[5,55,65],[7,87,97]],axis=0)

array([[ 25,  75, 175],
       [  5,  55,  65],
       [  9, 125, 150],
       [  4,  17, 225],
       [  7,  87,  97]])

In [87]:
np.insert(arr1,[1],[40,40,4000],axis=1)

array([[  25,   40,   40, 4000,   75,  175],
       [   9,   40,   40, 4000,  125,  150],
       [   4,   40,   40, 4000,   17,  225]])

In [88]:
np.insert(arr1,[1,3],[[40,50],[400,500],[40000,50000]],axis=1)

array([[   25,    40,    75,   175,    50],
       [    9,   400,   125,   150,   500],
       [    4, 40000,    17,   225, 50000]])

## Deletion

In [89]:
arr0

array([10, 17, 50])

In [90]:
np.delete(arr0,1)#Here 1 is the index

array([10, 50])

In [91]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [92]:
np.delete(arr1,1,axis=0)

array([[ 25,  75, 175],
       [  4,  17, 225]])

In [93]:
np.delete(arr1,1,axis=1)

array([[ 25, 175],
       [  9, 150],
       [  4, 225]])

## 15,16 march ,holiday 

## Holy----------->               Home Work

In [94]:
# 1.Complete the whole Python with project
# 2.SQL(TABULAR DATA)/NOSQL(UNSTRUCTURED DATA)<-----------COMPANY PURPOSE
# 3.Web Scraaping other than BeautifulSoup i.e Selenium,...

## Scalar Operation

In [95]:
arr1*2#Scalar works on each element

array([[ 50, 150, 350],
       [ 18, 250, 300],
       [  8,  34, 450]])

In [96]:
arr1/2

array([[ 12.5,  37.5,  87.5],
       [  4.5,  62.5,  75. ],
       [  2. ,   8.5, 112.5]])

## Vector Operation

In [97]:
# It works element wise and positionally
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [98]:
arr2=np.diag([10,10,10])

In [99]:
arr2

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [100]:
np.add(arr1,arr2)

array([[ 35,  75, 175],
       [  9, 135, 150],
       [  4,  17, 235]])

In [101]:
arr1+arr2#Above method is same like operator

array([[ 35,  75, 175],
       [  9, 135, 150],
       [  4,  17, 235]])

In [102]:
np.subtract(arr1,arr2)

array([[ 15,  75, 175],
       [  9, 115, 150],
       [  4,  17, 215]])

In [103]:
arr1-arr2

array([[ 15,  75, 175],
       [  9, 115, 150],
       [  4,  17, 215]])

In [104]:
np.multiply(arr1,arr2)

array([[ 250,    0,    0],
       [   0, 1250,    0],
       [   0,    0, 2250]])

In [105]:
arr1*arr2

array([[ 250,    0,    0],
       [   0, 1250,    0],
       [   0,    0, 2250]])

In [106]:
np.divide(arr1,arr2)#Here inf==infinite

/home/pankaj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 2.5,  inf,  inf],
       [ inf, 12.5,  inf],
       [ inf,  inf, 22.5]])

In [107]:
np.divide(arr2,arr1)

array([[0.4       , 0.        , 0.        ],
       [0.        , 0.08      , 0.        ],
       [0.        , 0.        , 0.04444444]])

In [108]:
np.power(arr2,2)

array([[100,   0,   0],
       [  0, 100,   0],
       [  0,   0, 100]])

In [109]:
np.sqrt(arr1)

array([[ 5.        ,  8.66025404, 13.22875656],
       [ 3.        , 11.18033989, 12.24744871],
       [ 2.        ,  4.12310563, 15.        ]])

In [110]:
np.exp(arr1)#e**something

array([[7.20048993e+10, 3.73324200e+32, 1.00353918e+76],
       [8.10308393e+03, 1.93557604e+54, 1.39370958e+65],
       [5.45981500e+01, 2.41549528e+07, 5.20305514e+97]])

In [111]:
np.log(arr1)

array([[3.21887582, 4.31748811, 5.16478597],
       [2.19722458, 4.82831374, 5.01063529],
       [1.38629436, 2.83321334, 5.4161004 ]])

## numpy.org tutorial # To get the notes for numpy(officially)

In [112]:
arr3=np.identity(3)
arr4=np.ones((3,3))

In [113]:
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
arr3==arr4

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [116]:
arr3[arr3==arr4]

array([1., 1., 1.])

In [117]:
arr4[arr3==arr4]

array([1., 1., 1.])

In [118]:
arr3[arr3>=arr4]

array([1., 1., 1.])

## Logical

In [119]:
np.logical_and(arr3,arr4)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## 23rd,February 2020

## Agrregate Function

In [120]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [121]:
# Overall max.
np.max(arr1)

225

In [122]:
np.min(arr1)

4

In [123]:
#min. along any specific axis
np.min(arr1,axis=0)# min. value along each column

array([  4,  17, 150])

In [124]:
np.max(arr1,axis=1)#max. value along axis

array([175, 150, 225])

In [125]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [126]:
np.argmin(arr1,axis=0)#along the column

array([2, 2, 1])

In [127]:
np.argmax(arr1,axis=1)#along the row

array([2, 2, 2])

In [128]:
# overall argmin
np.argmin(arr1)

6

In [129]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [130]:
np.sum(arr1,axis=0)#along the column

array([ 38, 217, 550])

In [131]:
np.sum(arr1,axis=1)#along the row

array([275, 284, 246])

## mode=3median-2mean

## frequenty occured no. in the given series is mode

## 5,8,7,5,6,8,9,7,3,5----------------->Mode============> 5

## mean=sum of all the given observation/no.of observation --> 63/10=>6.3

## arrange all the observation in ascending order and count no.of obseravation
if n==even==>divide by 2,then suppose on dividing by 2 it gives 6th term
            then we will take summation of 6th and 7th term and againg divide by 2
            will be our median
if n==odd--> n/2 will be your median

In [132]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [133]:
np.mean(arr1,axis=0)#here axis=0 means to collapse that axis

array([ 12.66666667,  72.33333333, 183.33333333])

In [134]:
(25+9+4)/3

12.666666666666666

In [135]:
np.product(arr1,axis=0)#along column

array([    900,  159375, 5906250])

In [136]:
np.product(arr1,axis=1)#along row

array([328125, 168750,  15300])

In [137]:
heights=np.loadtxt('/home/pankaj/Downloads/US_Pres_Height.csv',skiprows=1,unpack=True,
                  usecols=2,delimiter=',')
heights

array([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173.,
       173., 175., 178., 183., 193., 178., 173., 174., 183., 183., 168.,
       170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183.,
       193., 182., 183., 177., 185., 188., 188., 182., 185.])

In [138]:
4/3

1.3333333333333333

In [139]:
datas=np.loadtxt('/home/pankaj/Downloads/US_Pres_Height.csv',usecols=2,delimiter=','
                ,skiprows=1)
datas

array([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173.,
       173., 175., 178., 183., 193., 178., 173., 174., 183., 183., 168.,
       170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183.,
       193., 182., 183., 177., 185., 188., 188., 182., 185.])

In [140]:
heights

array([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173.,
       173., 175., 178., 183., 193., 178., 173., 174., 183., 183., 168.,
       170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183.,
       193., 182., 183., 177., 185., 188., 188., 182., 185.])

In [141]:
data=np.loadtxt('/home/pankaj/Downloads/US_Pres_Height.csv',unpack=False,
                  dtype='|S20',delimiter=',')
data

array([[b'order', b'name', b'height(cm)'],
       [b'1', b'George Washington', b'189'],
       [b'2', b'John Adams', b'170'],
       [b'3', b'Thomas Jefferson', b'189'],
       [b'4', b'James Madison', b'163'],
       [b'5', b'James Monroe', b'183'],
       [b'6', b'John Quincy Adams', b'171'],
       [b'7', b'Andrew Jackson', b'185'],
       [b'8', b'Martin Van Buren', b'168'],
       [b'9', b'William Henry Harris', b'173'],
       [b'10', b'John Tyler', b'183'],
       [b'11', b'James K. Polk', b'173'],
       [b'12', b'Zachary Taylor', b'173'],
       [b'13', b'Millard Fillmore', b'175'],
       [b'14', b'Franklin Pierce', b'178'],
       [b'15', b'James Buchanan', b'183'],
       [b'16', b'Abraham Lincoln', b'193'],
       [b'17', b'Andrew Johnson', b'178'],
       [b'18', b'Ulysses S. Grant', b'173'],
       [b'19', b'Rutherford B. Hayes', b'174'],
       [b'20', b'James A. Garfield', b'183'],
       [b'21', b'Chester A. Arthur', b'183'],
       [b'23', b'Benjamin Harrison', b'168

In [142]:
datas=np.loadtxt('/home/pankaj/Downloads/US_Pres_Height.csv',usecols=2,delimiter=','
                ,skiprows=1,unpack=True,dtype=np.int64)
datas

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185])

In [143]:
heights=np.loadtxt('/home/pankaj/Downloads/US_Pres_Height.csv',skiprows=1,unpack=True,delimiter=','
                   ,dtype=np.int64,usecols=2)                         

In [144]:
heights

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185])

In [145]:
heights.mean()
datas.mean()

179.73809523809524

In [146]:
np.max(heights)
np.max(datas)

193

In [147]:
max(heights)#python max

193

In [148]:
np.median(heights)#middle value is callled median
np.median(datas)

182.0

In [149]:
# mean=total no. of observation divide by total no. obserations
len(datas)
datas.size

42

In [150]:
arr0

array([10, 17, 50])

In [151]:
np.sort(arr0)#Default Ascending Order

array([10, 17, 50])

In [152]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [153]:
np.sort(arr1)

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [154]:
np.sort(arr1,axis=1)#Along rows

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [155]:
np.sort(arr1,axis=0)#Along columns
np.sort(arr1,axis=1)#Along rows

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [156]:
 np.std(heights)# standard variation means value is to vary
np.std(datas)

6.931843442745892

In [157]:
arr4=np.array([[1,2,3],[5,6,7]])
arr5=np.array([[6,7],[8,9],[10,11]])

In [158]:
arr5

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [159]:
arr4.shape,arr5.shape

((2, 3), (3, 2))

In [160]:
np.dot(arr4,arr5)#Dot product

array([[ 52,  58],
       [148, 166]])

In [161]:
np.cross(arr4,arr4)

array([[0, 0, 0],
       [0, 0, 0]])

In [162]:
 np.std(heights)# standard variation means value is to vary
np.std(datas)

6.931843442745892

## 29th,February 2020

In [163]:
arr1

array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [199]:
#transpose(means interchange of row to column and vice-versa)
arr1.T

array([[ 25,   9,   4],
       [ 75, 125,  17],
       [175, 150, 225]])

In [200]:
np.transpose(arr1)

array([[ 25,   9,   4],
       [ 75, 125,  17],
       [175, 150, 225]])

In [209]:
#concatenate
arr1


array([[ 25,  75, 175],
       [  9, 125, 150],
       [  4,  17, 225]])

In [210]:
arr7=np.ones((3,3))
arr7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [211]:
np.concatenate((arr1,arr7),axis=0)#vertical concatenation,arrays must have same no. of columns

array([[ 25.,  75., 175.],
       [  9., 125., 150.],
       [  4.,  17., 225.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [212]:
np.concatenate((arr1,arr7),axis=1)

array([[ 25.,  75., 175.,   1.,   1.,   1.],
       [  9., 125., 150.,   1.,   1.,   1.],
       [  4.,  17., 225.,   1.,   1.,   1.]])

In [216]:
np.vstack((arr1,arr7))# It is same as vertical concatenation

array([[ 25.,  75., 175.],
       [  9., 125., 150.],
       [  4.,  17., 225.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [217]:
np.hstack((arr1,arr7))

array([[ 25.,  75., 175.,   1.,   1.,   1.],
       [  9., 125., 150.,   1.,   1.,   1.],
       [  4.,  17., 225.,   1.,   1.,   1.]])

In [218]:
harr=np.hstack((arr1,arr7))
harr

array([[ 25.,  75., 175.,   1.,   1.,   1.],
       [  9., 125., 150.,   1.,   1.,   1.],
       [  4.,  17., 225.,   1.,   1.,   1.]])

In [219]:
harr.size

18

In [220]:
harr.shape

(3, 6)

In [227]:
harr.reshape(2,9)

array([[ 25.,  75., 175.,   1.,   1.,   1.,   9., 125., 150.],
       [  1.,   1.,   1.,   4.,  17., 225.,   1.,   1.,   1.]])

In [228]:
harr.reshape(6,3)

array([[ 25.,  75., 175.],
       [  1.,   1.,   1.],
       [  9., 125., 150.],
       [  1.,   1.,   1.],
       [  4.,  17., 225.],
       [  1.,   1.,   1.]])

In [229]:
harr.reshape(1,18)

array([[ 25.,  75., 175.,   1.,   1.,   1.,   9., 125., 150.,   1.,   1.,
          1.,   4.,  17., 225.,   1.,   1.,   1.]])

In [178]:
np.unique(harr)

array([  1.,   4.,   9.,  17.,  25.,  75., 125., 150., 175., 225.])

In [179]:
np.unique(harr,return_counts=True)

(array([  1.,   4.,   9.,  17.,  25.,  75., 125., 150., 175., 225.]),
 array([9, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [21]:
import numpy as np

In [22]:
data=np.loadtxt('/home/pankaj/Downloads/weather_2012.csv',skiprows=1,delimiter=',',
               usecols=[1,2,3,4,5,6])
data

array([[ -1.8 ,  -3.9 ,  86.  ,   4.  ,   8.  , 101.24],
       [ -1.8 ,  -3.7 ,  87.  ,   4.  ,   8.  , 101.24],
       [ -1.8 ,  -3.4 ,  89.  ,   7.  ,   4.  , 101.26],
       ...,
       [ -0.5 ,  -1.5 ,  93.  ,  28.  ,   4.8 ,  99.95],
       [ -0.2 ,  -1.8 ,  89.  ,  28.  ,   9.7 ,  99.91],
       [  0.  ,  -2.1 ,  86.  ,  30.  ,  11.3 ,  99.89]])

In [23]:
data.shape

(8784, 6)

In [24]:
temp=data[:,0]

In [25]:
temp.shape

(8784,)

In [27]:
fahrenheit=(temp*9/5)+32
fahrenheit

array([28.76, 28.76, 28.76, ..., 31.1 , 31.64, 32.  ])

In [32]:
dpt=data[:,1]

In [33]:
np.add(temp,dpt)

array([-5.7, -5.5, -5.2, ..., -2. , -2. , -2.1])

In [187]:
temp>0

array([False, False, False, ..., False, False, False])

In [188]:
print(temp>0)

[False False False ... False False False]


In [189]:
print(temp[temp>0])

[0.2 0.8 1.8 ... 0.6 0.1 0.2]


In [190]:
np.max(temp)

33.0

In [191]:
np.min(temp)

-23.3

In [192]:
min(temp),max(temp),np.mean(temp)

(-23.3, 33.0, 8.798144353369764)

In [193]:
np.mean(data,axis=0)

array([  8.79814435,   2.55529372,  67.43169399,  14.94546903,
        27.66444672, 101.05162341])

In [194]:
np.median(data,axis=0)

array([  9.3 ,   3.3 ,  68.  ,  13.  ,  25.  , 101.07])

In [195]:
#Data having visibilitry greater than 30km and temp above 32c
data[(data[:,-2]>30) & (data[:,0]>32)]


array([[ 32.1 ,  10.2 ,  26.  ,  20.  ,  48.3 , 101.49],
       [ 32.7 ,  15.3 ,  35.  ,  28.  ,  48.3 , 101.35],
       [ 33.  ,  16.8 ,  38.  ,  22.  ,  48.3 , 101.31],
       [ 32.9 ,  15.3 ,  35.  ,  24.  ,  48.3 , 101.26],
       [ 32.5 ,  16.5 ,  38.  ,  19.  ,  48.3 , 101.22]])