In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

# Numpy 1-D array creation1

In [4]:
a1=np.array([10,20,30])
a1

array([10, 20, 30])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2=np.array([10,20,3.5])
a2

array([10. , 20. ,  3.5])

In [7]:
a2.dtype

dtype('float64')

In [8]:
a2=np.array([10,20,3.5],dtype=np.int16)
a2

array([10, 20,  3], dtype=int16)

In [9]:
a2.dtype

dtype('int16')

In [10]:
a7=np.zeros(5)
a7

array([0., 0., 0., 0., 0.])

In [11]:
a8=np.zeros(5,dtype=np.int16)
a8

array([0, 0, 0, 0, 0], dtype=int16)

In [12]:
print(a7,a8)

[0. 0. 0. 0. 0.] [0 0 0 0 0]


In [13]:
a8=np.ones(6)
a8

array([1., 1., 1., 1., 1., 1.])

In [14]:
a9=np.full(3,10)
a9

array([10, 10, 10])

In [15]:
a10=np.random.random(5)
a10

array([0.79908824, 0.48732589, 0.05451093, 0.32869712, 0.80493569])

In [16]:
a11=np.random.uniform(2,10,5)
a11

array([2.50086787, 3.86943745, 3.23855043, 9.52888575, 8.92491567])

In [17]:
a12=np.random.randint(2,10,5)
a12

array([7, 5, 8, 6, 2])

In [18]:
a13=np.linspace(1,100,10)#lower,upper,num_of_elements
a14=np.linspace(1,100,5)#lower,upper,num_of_elements
a15=np.linspace(1,100)#lower,upper
print(a13,a14,a15,sep='\n')

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[  1.    25.75  50.5   75.25 100.  ]
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


# Numpy 2d-array creation1

In [19]:
a1=np.array([[1,2,3],[2,3,4],[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
type(a1)

numpy.ndarray

In [21]:
a1.dtype

dtype('int32')

Creating numpy array using list of list 
case-1
    >if all nested lists are same in size,2d array gets created.
    >in this case,default dtype will be type of elements present in nested
case-2
    >if any nested list is different in size,1d array gets created
    >in this case,default dtype will be listr

In [22]:
a2=np.array([[1,2],[2,3,4],[1,2,3],[4,5,6]])#Pay attend here on the output
a2

array([list([1, 2]), list([2, 3, 4]), list([1, 2, 3]), list([4, 5, 6])],
      dtype=object)

In [23]:
a2=np.zeros((3,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
a2=np.zeros([3,4])#The above and this statement is same
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
a3=np.ones((3,4))
a3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a4=np.full((3,4),5)
a4

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
a5=np.random.random((2,3))
a5

array([[0.67533463, 0.11851033, 0.8781287 ],
       [0.78896878, 0.39913409, 0.19671541]])

In [28]:
a6=np.random.uniform(1,5,(2,3))
a6

array([[1.75937015, 4.95360854, 1.32247834],
       [1.08429661, 3.91673102, 3.38775371]])

In [29]:
a7=np.random.randint(1,5,(2,3))
a7

array([[3, 1, 3],
       [3, 2, 1]])

In [30]:
a8=np.eye(3,3)
a8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Operations on numpy array

In [31]:
a1=np.random.randint(1,10,5)
a2=np.random.randint(1,10,(3,4))
a1

array([4, 1, 4, 9, 2])

In [32]:
a2

array([[1, 4, 7, 6],
       [4, 5, 5, 8],
       [3, 7, 8, 7]])

In [33]:
print(np.sum(a1),np.sum(a2),sep='\n')

20
65


In [34]:
print(np.sum(a2,axis=0),np.sum(a2,axis=1),sep='\n')#column,row wise

[ 8 16 20 21]
[18 22 25]


In [35]:
print(np.mean(a1))
print(np.mean(a2))
print(np.mean(a2,axis=1))#row wise
print(np.mean(a2,axis=0))#column wise

4.0
5.416666666666667
[4.5  5.5  6.25]
[2.66666667 5.33333333 6.66666667 7.        ]


In [36]:
print(np.max(a1))
print(np.max(a2))
print(np.max(a2,axis=1))#row wise
print(np.max(a2,axis=0))#column wise

9
8
[7 8 8]
[4 7 8 8]


In [37]:
print(np.argmin(a1))#argmin means index of the minimum value
print(np.argmax(a2))#argmax means index of the minimum value

1
7


# Lecture-2

In [38]:
import numpy as np

In [39]:
a=np.array([0,1,0,1,1,0,1,0,1,1,0])
np.bincount(a)

array([5, 6], dtype=int64)

In [42]:
a=np.array([0,1,4,3,9,3,7,8])
np.bincount(a)#It tell about all the value from 0 to 9
#It will not except negative or floating type value(It shows the value error on these two values(negative and floating value))

array([1, 1, 0, 2, 1, 0, 0, 1, 1, 1], dtype=int64)

In [45]:
a=np.array([3,2,5,6])
np.bincount(a)

array([0, 0, 1, 1, 0, 1, 1], dtype=int64)

In [50]:
a=np.random.randint(1,10,20)
a

array([9, 6, 6, 2, 8, 2, 8, 7, 6, 7, 2, 2, 7, 9, 3, 3, 8, 9, 8, 3])

In [51]:
np.unique(a)

array([2, 3, 6, 7, 8, 9])

In [52]:
a1=np.random.randint(1,4,[2,2])
a1

array([[1, 1],
       [2, 2]])

In [55]:
a1*5#Scaler multiplication

array([[ 5,  5],
       [10, 10]])

In [57]:
a1=np.random.randint(1,4,[2,2])
a2=np.random.randint(1,4,[2,2])

In [60]:
print(a1,a2,sep='\n')

[[1 3]
 [3 2]]
[[3 1]
 [3 1]]


In [61]:
a1*a2#Arithmetic multiplication of two matrix

array([[3, 3],
       [9, 2]])

In [62]:
a1@a2#Matrix multiplication of two matrix

array([[12,  4],
       [15,  5]])

In [64]:
np.dot(a1,a2)#Always work independent of version

array([[12,  4],
       [15,  5]])

In [65]:
a1-a2#Arithmetic subtraction

array([[-2,  2],
       [ 0,  1]])

In [66]:
a=np.random.randint(1,10,10)
a

array([6, 8, 6, 1, 2, 1, 8, 5, 2, 2])

In [67]:
np.square(-1)

1

In [69]:
print(np.square(3))
print(np.square(a))

9
[36 64 36  1  4  1 64 25  4  4]


In [70]:
a1

array([[1, 3],
       [3, 2]])

In [71]:
np.square(a1)

array([[1, 9],
       [9, 4]], dtype=int32)

In [72]:
print(np.sqrt(9))
print(np.sqrt(a))
print(np.sqrt(a1))

3.0
[2.44948974 2.82842712 2.44948974 1.         1.41421356 1.
 2.82842712 2.23606798 1.41421356 1.41421356]
[[1.         1.73205081]
 [1.73205081 1.41421356]]


In [73]:
np.exp(0)

1.0

In [74]:
np.exp(a),np.exp(a1)

(array([4.03428793e+02, 2.98095799e+03, 4.03428793e+02, 2.71828183e+00,
        7.38905610e+00, 2.71828183e+00, 2.98095799e+03, 1.48413159e+02,
        7.38905610e+00, 7.38905610e+00]),
 array([[ 2.71828183, 20.08553692],
        [20.08553692,  7.3890561 ]]))

In [75]:
np.log(a)#Natural log with base e

array([1.79175947, 2.07944154, 1.79175947, 0.        , 0.69314718,
       0.        , 2.07944154, 1.60943791, 0.69314718, 0.69314718])

In [77]:
np.log2(a)#base 1

array([2.5849625 , 3.        , 2.5849625 , 0.        , 1.        ,
       0.        , 3.        , 2.32192809, 1.        , 1.        ])

In [78]:
np.log10(a)#base 10

array([0.77815125, 0.90308999, 0.77815125, 0.        , 0.30103   ,
       0.        , 0.90308999, 0.69897   , 0.30103   , 0.30103   ])

In [83]:
a=np.loadtxt('c:/Users/Dell/Documents/num1.txt',delimiter='\n')
a

array([10., 20.,  5., -3.,  6., 20., 40., 20.])

In [84]:
a=np.loadtxt('c:/Users/Dell/Documents/num1.txt',delimiter=',')#Here delimiter is comma(but how it's working)
a

array([10., 20.,  5., -3.,  6., 20., 40., 20.])

In [119]:
a=np.random.randint(1,5,10)
a

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [120]:
np.savetxt('num3.txt',a)

In [121]:
np.savetxt('num3.txt',a,fmt='%.1f')
print('Text is saved')

Text is saved


In [122]:
np.savetxt('num4.txt',a,fmt='%.1f',newline=',')
print('Text is saved just now!')

Text is saved just now!


In [123]:
print(len(a),a.size,sep='\n')

10
10


In [124]:
np.reshape(a,(5,2))

array([[1, 2],
       [1, 3],
       [4, 1],
       [1, 1],
       [4, 4]])

In [125]:
a

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [126]:
a.reshape(5,2)#a.reshape(row,column)

array([[1, 2],
       [1, 3],
       [4, 1],
       [1, 1],
       [4, 4]])

In [127]:
# a.reshape(3,3)#<---ValueError: cannot reshape array of size 10 into shape (3,3)

In [128]:
a.reshape(10,1)

array([[1],
       [2],
       [1],
       [3],
       [4],
       [1],
       [1],
       [1],
       [4],
       [4]])

In [129]:
a.reshape(1,10)

array([[1, 2, 1, 3, 4, 1, 1, 1, 4, 4]])

In [130]:
a.reshape(2,5)

array([[1, 2, 1, 3, 4],
       [1, 1, 1, 4, 4]])

In [131]:
a.resize(2,5)

In [132]:
a

array([[1, 2, 1, 3, 4],
       [1, 1, 1, 4, 4]])

In [134]:
# reshape doesn't make change in the existing array while resize make  
# changes in the existing array 

In [135]:
a.flatten()

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [138]:
a

array([[1, 2, 1, 3, 4],
       [1, 1, 1, 4, 4]])

## Note:mostly operations in numpy return a copy

In [140]:
a1=np.random.randint(1,5,(3,3))
a2=np.random.randint(1,5,(3,3))

In [141]:
a1

array([[4, 3, 4],
       [3, 4, 3],
       [4, 4, 3]])

In [142]:
a2

array([[3, 1, 3],
       [4, 3, 3],
       [1, 3, 4]])

In [143]:
np.vstack((a1,a2))

array([[4, 3, 4],
       [3, 4, 3],
       [4, 4, 3],
       [3, 1, 3],
       [4, 3, 3],
       [1, 3, 4]])

In [144]:
np.hstack((a1,a2))

array([[4, 3, 4, 3, 1, 3],
       [3, 4, 3, 4, 3, 3],
       [4, 4, 3, 1, 3, 4]])

# Numpy Variables

In [146]:
a

array([[1, 2, 1, 3, 4],
       [1, 1, 1, 4, 4]])

In [148]:
a.shape#returns a tuple reperesenting no. of elements in each dimention

(2, 5)

In [149]:
a

array([[1, 2, 1, 3, 4],
       [1, 1, 1, 4, 4]])

In [150]:
a1.shape

(3, 3)

In [151]:
a.shape[0]

2

In [152]:
a.shape[1]

5

In [153]:
a.ndim#returns dimention of array

2

In [154]:
a.size#Total no. of elements in array

10

In [155]:
len(a)#length of array

2

In [156]:
a.dtype#returns datatype of array-elements

dtype('int32')

In [157]:
a=a.flatten()

In [158]:
a

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [159]:
np.append(a,50)

array([ 1,  2,  1,  3,  4,  1,  1,  1,  4,  4, 50])

In [160]:
a

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [161]:
np.insert(a,0,100)

array([100,   1,   2,   1,   3,   4,   1,   1,   1,   4,   4])

In [162]:
np.delete(a,0)

array([2, 1, 3, 4, 1, 1, 1, 4, 4])

In [163]:
np.delete(a,[0,2])

array([2, 3, 4, 1, 1, 1, 4, 4])

In [164]:
a

array([1, 2, 1, 3, 4, 1, 1, 1, 4, 4])

In [167]:
a[0]=10#It changes in existing array

In [168]:
a

array([10,  2,  1,  3,  4,  1,  1,  1,  4,  4])

In [169]:
a[2]

1

In [170]:
a[2:]

array([1, 3, 4, 1, 1, 1, 4, 4])

In [171]:
a[-1]

4

In [172]:
b=a+1

In [173]:
b

array([11,  3,  2,  4,  5,  2,  2,  2,  5,  5])

In [174]:
a1=np.array([1,2,3,4,10,20])
a2=np.array([1,2,5,4,100,20])

In [175]:
np.where(a1==a2)

(array([0, 1, 3, 5], dtype=int64),)

In [176]:
a1==a2

array([ True,  True, False,  True, False,  True])

In [177]:
np.where(a1!=a2)

(array([2, 4], dtype=int64),)

In [178]:
np.where(a1>a2)

(array([], dtype=int64),)

In [179]:
np.where(a1<a2)

(array([2, 4], dtype=int64),)

In [181]:
a1[a1%2==0]#Getting even values from a1

array([ 2,  4, 10, 20])

In [182]:
a1[a1>5]

array([10, 20])

In [183]:
#a1[(a1%2==0) and (a1>5)]#Here it will generate error due logical and operator ,there should be bitwise &

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [184]:
a1[(a1%2==0) & (a1>5)]

array([10, 20])

In [185]:
a1[(a1%2==0) & (a1>5)]

array([10, 20])

In [186]:
a1

array([ 1,  2,  3,  4, 10, 20])

In [187]:
np.mean(a1)

6.666666666666667

In [188]:
a1.mean()

6.666666666666667

In [189]:
np.median(a1)

3.5

In [190]:
a=np.array([2000,2500,2200,2100,2600])
print(np.mean(a))
print(np.median(a))

2280.0
2200.0


In [191]:
a=np.array([2000,2500,2200,2100,26000])
print(np.mean(a))
print(np.median(a))

6960.0
2200.0


In [192]:
# mean and median is used for outlier value (2600 in the array a)

In [193]:
a=np.array([2000,2500,2200,2100,26000])
print(np.std(a))

9521.47047466934


In [194]:
a=np.array([2000,2500,2200,2100,2600])
print(np.std(a))

231.5167380558045
