In [ ]:
#Cheat Sheet for numpy
array1.ndim
array1.shape
array1.size
array1.itemsize

np.may_share_memory(array1,array2)
ar2 = array1[0:2].copy()#It is the shollow copy of the array

array2 = np.append(array1,100)
array3 = np.append(array1,[10,20])

array4 = np.insert(array3,1,50)
array4 = np.insert(array3,1,50)

array6 = np.delete(array5, 4)#Here 4 is the index

array7 = array6+2
array8 = array6*2
array9 = np.arange(1,10,2)
array10 = np.linspace(10,99,10)

# 1 6 11 12
r_index = np.array([0,1,2,2])
c_index = np.array([0,1,2,3])
array5[r_index,c_index]

array8 = array7.flatten()
np.append(array5,[[12,13,14,15]], axis=0)#  axis=0 means across the row
np.append(array5,[[12],[13],[14]], axis=1)# axis=1 means across the column

axis = 0, along rows
axis = 1, along column
# Bydefault if 'axis' is not provided then insert() will flatten the array
np.delete(array5,2, axis=0)
np.delete(array5,2, axis=1)

np.zeros((2,2))   # Null Matrix
np.full((2,3), 5) #Scalar Matrix
np.eye(3,3) #Square identity matrix
np.diag([1,2,3]) # Diagonal matrix
np.diag(array5)
np.empty((3,2))

np.random.rand(2,2)
# rand() return random numbers from uniform distribution over [0, 1)
np.random.randn(2,2)
#randn() return random numbers from standard normal distribution with mean 0 
# and variance 1.
np.random.random((3,2))
# random() return random number from continuous uniform distribution.
np.random.randint(0,10,(3,2))

np.add(array6,array7)
np.subtract(array6,array7)#  is equal to array6-array7
np.multiply(array6,array7) # it is same as array6*array7
np.divide(array6,array7)
np.square(array6)
np.sqrt(array6)


**Numpy(Numeric Python):** Open Source python Library for higher level mathematical function (scientific computing). Also known as array computing.

- It's an extension package to python for multidimensional arrays.
- It was introduced(by Travis Oliphant) in 2005 and distributed as open source library.
- It is not the part of default python and we need to download it by using pip utility
    - cmd>pip install numpy
    - It is also bundled with anaconda software.

**Array:** An array is a data structure that stores values of same data type.

In [8]:
import numpy as np

In [9]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

# - ndarray.ndim
    - the number of axes (dimensions) of the array.

In [3]:
array1.ndim # Check dimension

1

In [4]:
array1.shape # shape of array

(4,)

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.size #no. of elements in array

4

In [7]:
array1.dtype

dtype('int64')

In [8]:
array1.itemsize # length of one array element in bytes

8

In [9]:
array1[0] # forward indexing

1

In [10]:
array1[-1] # backward indexing

4

In [11]:
array1[[0,3]] # Access multiple elements

array([1, 4])

In [12]:
array1[::-1]

array([4, 3, 2, 1])

In [13]:
ar1 = array1[1:3]
ar1

array([2, 3])

In [14]:
np.may_share_memory(array1,ar1)

True

In [15]:
ar1[0]

2

In [16]:
ar1[0] = 100 # Assignment

In [17]:
ar1

array([100,   3])

In [18]:
array1

array([  1, 100,   3,   4])

In [19]:
ar2 = array1[0:2].copy()#It is the shollow copy of the array
ar2

array([  1, 100])

In [20]:
ar2[1] = 5
ar2

array([1, 5])

In [21]:
array1

array([  1, 100,   3,   4])

In [22]:
import sys
a0 = [1,2,3,4]
print(sys.getsizeof(1)*len(a0))

a1 = np.array([1,2,3,4])
print(a1.size*a1.itemsize)

112
32


In [23]:
#array1[0]='hi'
array1

array([  1, 100,   3,   4])

In [24]:
array2 = np.append(array1,100)
array2

array([  1, 100,   3,   4, 100])

In [25]:
array3 = np.append(array1,[10,20])
array3
# values are appended to a copy of Original array with 
# new reference in memory

array([  1, 100,   3,   4,  10,  20])

In [26]:
array4 = np.insert(array3,1,50)
array4
# values are inserted at particular index to a copy of Original 
# array with new reference in memory

array([  1,  50, 100,   3,   4,  10,  20])

In [27]:
array5 = np.insert(array4,1,[10,10])
array5

array([  1,  10,  10,  50, 100,   3,   4,  10,  20])

In [28]:
array6 = np.delete(array5, 4)
array6

array([ 1, 10, 10, 50,  3,  4, 10, 20])

In [29]:
array7 = array6+2
array7

array([ 3, 12, 12, 52,  5,  6, 12, 22])

In [30]:
list1 = [1,2,3,4]
print(list1*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [31]:
array8 = array6*2
array8

array([  2,  20,  20, 100,   6,   8,  20,  40])

In [32]:
array9 = np.arange(1,10,2)
array9

array([1, 3, 5, 7, 9])

In [33]:
array10 = np.linspace(10,99,10)
array10

array([10.        , 19.88888889, 29.77777778, 39.66666667, 49.55555556,
       59.44444444, 69.33333333, 79.22222222, 89.11111111, 99.        ])

In [34]:
array11 = np.array([[1,2,3,4],[5,6,7,8]])
array11

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
array12 = np.array([[1,2,3,4]])
array12

array([[1, 2, 3, 4]])

In [36]:
array12.shape

(1, 4)

In [37]:
array12.ndim

2

In [38]:
array11[1]

array([5, 6, 7, 8])

In [39]:
array11[1][0]

5

In [40]:
array11[1,0]

5

In [41]:
array11[1,3]

8

In [82]:
array11

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
array11[::,1:3]

array([[2, 3],
       [6, 7]])

In [43]:
array11[0:2,0:3:2]

array([[1, 3],
       [5, 7]])

In [44]:
array5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
#[[2 3
#  6 7]]
array5[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [46]:
# [[6,8
# 10,12]]
array5[1:,1::2]

array([[ 6,  8],
       [10, 12]])

In [47]:
#[[11,10
#  3, 2]]
array5[-1::-2, -2:-4:-1]

array([[11, 10],
       [ 3,  2]])

In [48]:
array5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
array5[1, :]

array([5, 6, 7, 8])

In [50]:
array5[1:2, :]

array([[5, 6, 7, 8]])

In [51]:
array5[:,-2]

array([ 3,  7, 11])

In [52]:
array5[:,-2:-1]

array([[ 3],
       [ 7],
       [11]])

In [53]:
# 1 6 11 12
r_index = np.array([0,1,2,2])
c_index = np.array([0,1,2,3])
array5[r_index,c_index]

array([ 1,  6, 11, 12])

In [54]:
array5[r_index,c_index] += 100
array5

array([[101,   2,   3,   4],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112]])

In [55]:
array5

array([[101,   2,   3,   4],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112]])

In [56]:
array6 = np.append(array5,[14,13,12])
array6
# Bydefault if 'axis' is not provided then append() will flatten the array

array([101,   2,   3,   4,   5, 106,   7,   8,   9,  10, 111, 112,  14,
        13,  12])

In [ ]:
# Bydefault if 'axis' is not provided then append() will flatten the array
np.append(array5,[[12,13,14,15]], axis=0)
np.append(array5,[[12],[13],[14]], axis=1)


In [57]:
array7 = array5.copy()
array8 = array7.flatten()
array8

array([101,   2,   3,   4,   5, 106,   7,   8,   9,  10, 111, 112])

axis = 0, along rows


axis = 1, along column

In [58]:
array5

array([[101,   2,   3,   4],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112]])

In [59]:
np.append(array5,[[12,13,14,15]], axis=0)

array([[101,   2,   3,   4],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112],
       [ 12,  13,  14,  15]])

In [60]:
np.append(array5,[[12],[13],[14]], axis=1)

array([[101,   2,   3,   4,  12],
       [  5, 106,   7,   8,  13],
       [  9,  10, 111, 112,  14]])

In [61]:
array5

array([[101,   2,   3,   4],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112]])

In [62]:
np.insert(array5,1,[5,10,15])
# Bydefault if 'axis' is not provided then insert() will flatten the array

array([101,   5,  10,  15,   2,   3,   4,   5, 106,   7,   8,   9,  10,
       111, 112])

In [63]:
np.insert(array5,1,[5,10,15,20], axis=0)

array([[101,   2,   3,   4],
       [  5,  10,  15,  20],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112]])

In [64]:
np.insert(array5,[1,3],[[5,10,15,20],[20,30,40,50]], axis=0)

array([[101,   2,   3,   4],
       [  5,  10,  15,  20],
       [  5, 106,   7,   8],
       [  9,  10, 111, 112],
       [ 20,  30,  40,  50]])

In [65]:
np.insert(array5,[1,3],[[12,13],[12,13],[12,13]], axis=1) # Multiple insertion

array([[101,  12,   2,   3,  13,   4],
       [  5,  12, 106,   7,  13,   8],
       [  9,  12,  10, 111,  13, 112]])

In [66]:
array5.flatten()

array([101,   2,   3,   4,   5, 106,   7,   8,   9,  10, 111, 112])

In [67]:
np.delete(array5,2)

array([101,   2,   4,   5, 106,   7,   8,   9,  10, 111, 112])

In [68]:
np.delete(array5,2, axis=0)

array([[101,   2,   3,   4],
       [  5, 106,   7,   8]])

In [69]:
np.delete(array5,2, axis=1)

array([[101,   2,   4],
       [  5, 106,   8],
       [  9,  10, 112]])

In [70]:
np.zeros((2,2)) # Null Matrix

array([[0., 0.],
       [0., 0.]])

In [71]:
# User defined numpy array
r = int(input("Enter no. of rows: "))
c = int(input("Enter no. of columns: "))
arr= np.zeros((r,c))

for i in range(r):
    for j in range(c):
        arr[i][j] = float(input('Enter value: '))
        
print(arr)

Enter no. of rows: 3
Enter no. of columns: 3
Enter value: 1
Enter value: 2
Enter value: 3
Enter value: 4
Enter value: 5
Enter value: 6
Enter value: 7
Enter value: 8
Enter value: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [72]:
np.full((2,3), 5) #Scalar Matrix

array([[5, 5, 5],
       [5, 5, 5]])

In [73]:
np.eye(3,3) #Square identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.diag([1,2,3]) # Diagonal matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [75]:
np.diag(array5)

array([101, 106, 111])

In [76]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
np.random.rand(2,2)
# rand() return random numbers from uniform distribution over [0, 1)

array([[0.99920338, 0.36230754],
       [0.49864272, 0.13274852]])

In [79]:
np.random.randn(2,2)
#randn() return random numbers from standard normal distribution with mean 0 
# and variance 1.

array([[ 1.37181338,  1.42724311],
       [-0.38347175,  0.80817671]])

In [80]:
np.random.random((3,2))
# random() return random number from continuous uniform distribution.

array([[0.72436561, 0.20968423],
       [0.68564855, 0.59134127],
       [0.64309081, 0.58971906]])

In [81]:
np.random.randint(0,10,(3,2))

array([[2, 5],
       [1, 8],
       [7, 6]])