# Built-in function

In [1]:
import numpy as np
#arange(start,stop,step)
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
x=np.arange(1,11,1)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#linspace(start,stop,num)#equally spaced no.
np.linspace(0,10,11)#here startin_point and end_point both is included

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
np.linspace(0,10,10,endpoint=False)# 10 will not included

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# null matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# ones()
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
#This is done by me
l=[111,333,444,555,666,777]
x=np.diag([1,2,3])
for i in x:
    for j in range(len(i)):
        if i[j]==0:
            i[j]=l[j]
print(x)

[[  1 333 444]
 [111   2 444]
 [111 333   3]]


In [10]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [11]:
np.random.rand(2,3)#rand() returns an array of given shape with samples
#from a uniform distribution over[0,1)

array([[0.90412246, 0.05789138, 0.8937858 ],
       [0.22252436, 0.07250005, 0.0898744 ]])

In [12]:
np.random.randn(2,3)
# randn() (n stands for normal) return an arry of given shape 
#populated with random samples from a standard normal distribution
#(Gausian Distribution) with mean 0 and variance 1.

array([[-0.22840048,  0.72051376,  0.92089412],
       [-1.65252071, -1.9920328 , -1.0971529 ]])

In [13]:
np.random.random((2,3))#return random number from continuous 
#uniform distribution

array([[0.08040996, 0.31940213, 0.44196714],
       [0.00480037, 0.28530896, 0.88041271]])

In [14]:
np.random.randint(4,40,10)# 4 inclusive anad 40 exclusive

array([10, 16, 33, 39, 21,  6, 17, 16, 26, 29])

In [15]:
np.random.randint(4,40,(3,3))# 4 inclusive anad 40 exclusive

array([[ 5, 31, 33],
       [18, 15, 17],
       [34, 39,  4]])

In [16]:
np.random.seed(0)
np.random.randint(4,40,(3,3))

array([[ 4,  7,  7],
       [13, 23, 25],
       [27, 10, 28]])

In [17]:
arr0=np.array([4,10,1])
arr0

array([ 4, 10,  1])

In [18]:
#indexing
arr0[2],arr0[-1]             

(1, 1)

In [19]:
arr0[::]

array([ 4, 10,  1])

In [20]:
arr0[::-1]

array([ 1, 10,  4])

In [21]:
arr0[-2::-1]

array([10,  4])

In [22]:
arr0*2

array([ 8, 20,  2])

### 22nd,January 2020

In [23]:
import numpy as np
data=[[5,15,35],[9,25,30],[4,17,25],[5,18,32]]
arr1=np.array(data)
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 25],
       [ 5, 18, 32]])

In [24]:
#slicing
#[[ 5, 15],
#[ 9, 25]])
arr1[:2,:2]

array([[ 5, 15],
       [ 9, 25]])

In [25]:
arr1[::3,::2]#<--------------

array([[ 5, 35],
       [ 5, 32]])

In [26]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 25],
       [ 5, 18, 32]])

In [27]:
x=arr1[-1::-2,-1:-3:-1]
print(x)
y=arr1[-1:-4:-2,-1:-3:-1]
print(y)
z=arr1[-2::-2,-1::-2]
print(z)

[[32 18]
 [30 25]]
[[32 18]
 [30 25]]
[[25  4]
 [35  5]]


In [28]:
arr4=arr1[-1::-2,-1:-3:-1]
arr4

array([[32, 18],
       [30, 25]])

In [29]:
arr4[0,0]=30
arr4

array([[30, 18],
       [30, 25]])

In [30]:
arr1

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 25],
       [ 5, 18, 30]])

In [31]:
arr4[0,0]=430
arr4

array([[430,  18],
       [ 30,  25]])

In [32]:
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [33]:
arr6=arr1[-1:-4:-2,-1:-3:-1].copy()#shallow copy,it creates different copy in the memory beside arr1
arr6

array([[430,  18],
       [ 30,  25]])

In [34]:
arr6[1,1]=250
arr6

array([[430,  18],
       [ 30, 250]])

In [35]:
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [36]:
# unordered slicing
#5-->(0,0)
#25-->(1,1)
#17-->(2,1)
#320-->(3,2)
row_index=[0,1,2,3]
col_index=[0,1,1,2]
arr1[row_index,col_index]

array([  5,  25,  17, 430])

In [37]:
#filtering(condition)/bollean indexing
arr1%2==0


array([[False, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True,  True]])

In [38]:
arr1[arr1%2==0]

array([ 30,   4,  18, 430])

In [39]:
arr0

array([ 4, 10,  1])

In [40]:
#append() method in numpy
np.append(arr0,5)# it doesn't voilate the original array
# it returns a copy only

array([ 4, 10,  1,  5])

In [41]:
np.append(arr0,[2,5])

array([ 4, 10,  1,  2,  5])

In [42]:
arr0

array([ 4, 10,  1])

In [43]:
np.insert(arr0,2,11)

array([ 4, 10, 11,  1])

In [44]:
np.insert(arr0,0,[44,444])

array([ 44, 444,   4,  10,   1])

In [45]:
np.insert(arr0,[1,2],[555,555])

array([  4, 555,  10, 555,   1])

In [46]:
# 2-D array
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [47]:
np.append(arr1,[[6,20,35]])

array([  5,  15,  35,   9,  25,  30,   4,  17,  25,   5,  18, 430,   6,
        20,  35])

In [48]:
np.append(arr1,[[6,20,35]],axis=0)#axis=0 ==>row
                                  #axis=1 ==>column

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430],
       [  6,  20,  35]])

In [49]:
np.append(arr1,[[2],[3],[5],[44]],axis=1)

array([[  5,  15,  35,   2],
       [  9,  25,  30,   3],
       [  4,  17,  25,   5],
       [  5,  18, 430,  44]])

In [50]:
np.insert(arr1,0,[[1,2,3]],axis=0)

array([[  1,   2,   3],
       [  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [51]:
np.insert(arr1,0,[[1,2,3,4]],axis=1)

array([[  1,   5,  15,  35],
       [  2,   9,  25,  30],
       [  3,   4,  17,  25],
       [  4,   5,  18, 430]])

In [52]:
arr0

array([ 4, 10,  1])

In [53]:
np.delete(arr0,2)# data at index 1 will be deleted

array([ 4, 10])

In [54]:
np.delete(arr0,[1,2])

array([4])

In [55]:
#2-Dimention
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [56]:
np.delete(arr1,3,axis=0)

array([[ 5, 15, 35],
       [ 9, 25, 30],
       [ 4, 17, 25]])

In [57]:
np.delete(arr1,2,axis=1)

array([[ 5, 15],
       [ 9, 25],
       [ 4, 17],
       [ 5, 18]])

In [58]:
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [59]:
arr1+5#scaler operation

array([[ 10,  20,  40],
       [ 14,  30,  35],
       [  9,  22,  30],
       [ 10,  23, 435]])

In [60]:
arr1*3# Any operation of an array with a scaler will result in element-wise computation ot that
#operation

array([[  15,   45,  105],
       [  27,   75,   90],
       [  12,   51,   75],
       [  15,   54, 1290]])

In [61]:
arr5=np.ones((4,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
arr1

array([[  5,  15,  35],
       [  9,  25,  30],
       [  4,  17,  25],
       [  5,  18, 430]])

In [63]:
arr1+arr5#All ooperations between arrays are positionally element-wise

array([[  6.,  16.,  36.],
       [ 10.,  26.,  31.],
       [  5.,  18.,  26.],
       [  6.,  19., 431.]])

In [64]:
np.add(arr1,arr5)

array([[  6.,  16.,  36.],
       [ 10.,  26.,  31.],
       [  5.,  18.,  26.],
       [  6.,  19., 431.]])

In [65]:
#np.subtract()
#np.multiply()
#np.divide()
np.divide(arr5,arr1)

array([[0.2       , 0.06666667, 0.02857143],
       [0.11111111, 0.04      , 0.03333333],
       [0.25      , 0.05882353, 0.04      ],
       [0.2       , 0.05555556, 0.00232558]])

In [66]:
np.power(arr1,2)

array([[    25,    225,   1225],
       [    81,    625,    900],
       [    16,    289,    625],
       [    25,    324, 184900]])

In [67]:
np.sqrt(arr5)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.exp(arr5)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [69]:
# to take log(natural log)
np.log(arr5)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.sin(np.pi/2)

1.0

In [71]:
np.tan(np.pi/3)

1.7320508075688767

In [72]:
np.around(np.log(arr1),decimals=2)#round() in python
                                  #around() in numpy

array([[1.61, 2.71, 3.56],
       [2.2 , 3.22, 3.4 ],
       [1.39, 2.83, 3.22],
       [1.61, 2.89, 6.06]])

In [73]:
# round() in python
x=5/3
print(x)
print(round(x,2))

1.6666666666666667
1.67


## 23rd,January 2020

In [74]:
import numpy as np
data=np.loadtxt('/home/pankaj/Downloads/Sample text.txt',delimiter=',')
data
#A delimiter is a sequence of one or more characters used to specify the boundary
#between separate, independent regions in plain text or other data streams.
#https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjexLmErJrnAhXG6XMBHeJJA5QQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.w3resource.com%2Fpython-exercises%2Fre%2Fpython-re-exercise-47.php&psig=AOvVaw1-KEtT62vxd6WAv6bupEY5&ust=1579890256630704

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.],
       [ 4.,  1.],
       [ 5.,  9.],
       [ 6.,  0.],
       [ 7., -5.],
       [ 8.,  3.],
       [ 9.,  2.],
       [10.,  9.]])

In [75]:
data.shape

(10, 2)

In [76]:
data.dtype#it tells each element type

dtype('float64')

In [77]:
type(data)

numpy.ndarray

In [78]:
value1=data[0]
value1

array([1., 4.])

In [82]:
value2=data[:,1]#column - 2
value2

array([ 4.,  5.,  6.,  1.,  9.,  0., -5.,  3.,  2.,  9.])

In [91]:
weather_data=np.genfromtxt('/home/pankaj/Downloads/weather_2012.csv',delimiter=',')
weather_data


array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,  -1.8 ,  -3.9 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.7 , ...,   4.  ,   8.  , 101.24],
       ...,
       [   nan,  -0.5 ,  -1.5 , ...,  28.  ,   4.8 ,  99.95],
       [   nan,  -0.2 ,  -1.8 , ...,  28.  ,   9.7 ,  99.91],
       [   nan,   0.  ,  -2.1 , ...,  30.  ,  11.3 ,  99.89]])

In [96]:
weather_data=np.genfromtxt('/home/pankaj/Downloads/weather_2012.csv',delimiter=',',
                          skip_header=1)# skip_header=1 ,to skip the row 1st
weather_data


array([[   nan,  -1.8 ,  -3.9 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.7 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.4 , ...,   7.  ,   4.  , 101.26],
       ...,
       [   nan,  -0.5 ,  -1.5 , ...,  28.  ,   4.8 ,  99.95],
       [   nan,  -0.2 ,  -1.8 , ...,  28.  ,   9.7 ,  99.91],
       [   nan,   0.  ,  -2.1 , ...,  30.  ,  11.3 ,  99.89]])

In [98]:
weather_data=np.genfromtxt('/home/pankaj/Downloads/weather_2012.csv',delimiter=',',
                          skip_header=1,dtype='|S20')#dtype <---------------ask to sir
weather_data


array([[b'01-01-2012 0:00', b'-1.8', b'-3.9', ..., b'4', b'8', b'101.24'],
       [b'01-01-2012 1:00', b'-1.8', b'-3.7', ..., b'4', b'8', b'101.24'],
       [b'01-01-2012 2:00', b'-1.8', b'-3.4', ..., b'7', b'4', b'101.26'],
       ...,
       [b'31-12-2012 21:00', b'-0.5', b'-1.5', ..., b'28', b'4.8',
        b'99.95'],
       [b'31-12-2012 22:00', b'-0.2', b'-1.8', ..., b'28', b'9.7',
        b'99.91'],
       [b'31-12-2012 23:00', b'0', b'-2.1', ..., b'30', b'11.3',
        b'99.89']], dtype='|S20')