In [2]:
import numpy as np
vector=np.arange(15,55)#It's a vector
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [34]:
import numpy as np
x=np.random.normal(0,1,15)
x

array([ 1.81073623, -0.49572164, -0.88267007, -0.07514817, -0.12841382,
       -0.78840415,  1.14140209, -1.75123023, -0.302011  , -0.88659353,
        0.2284008 , -0.38897441, -1.92344777, -0.56384193,  0.16821597])

In [27]:
import numpy as np
for i in range(10):
    print(np.random.normal(0,1,1))




[1.28703627]
[-0.71042304]
[2.58235661]
[-0.42659122]
[-1.33268065]
[-1.73119439]
[-1.05520385]
[-0.18401448]
[1.98286972]
[-0.21533884]


In [5]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np
array=np.arange(30,71,2)
array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [46]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
import numpy as np
range=np.arange(30,71)
print(range,type(range))


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70] <class 'numpy.ndarray'>


In [39]:
import numpy as np
print(np.zeros(10),np.ones(10),np.ones(10)*5,sep='\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [32]:
import numpy as np
a=np.array([1, 7, 13, 105])
# print(a.size)
print(f'{a.size*a.itemsize} bytes')

32 bytes


In [24]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
# print(x==y)
print(np.equal(x,y))
print(np.allclose(x,y))

[ True  True  True  True  True  True  True  True  True False]
True


In [22]:
import numpy as  np
a1=np.array([1,2,3])
a2=np.array([1,2,5])
print(a1>a2,a1>=a2,a1<a2,a1<=a2,sep='\n')


[False False False]
[ True  True False]
[False False  True]
[ True  True  True]


In [18]:
import numpy as  np
a1=np.array([1,2,3])
a2=np.array([1,2,2])
print(a1==a2)

[ True  True False]


In [11]:
import numpy as np
l=[1+3j,3j,3.4,np.nan,np.inf,3]
a=np.array(l)
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(a))
print(np.isscalar(3.2))

[ True  True False False False False]
[False False  True  True  True  True]
False
True


In [1]:
import numpy as np
l=[1,2,np.nan,np.inf]
array=np.array(l)
print(np.isnan(array))

[False False  True False]


In [22]:
import numpy as np
# print(dir(np))
print(np.__version__)#It is showing the latest version of the numpy module
print(np.show_config())#It shows the configuration of the numpy module


1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/pankaj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/pankaj/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/pankaj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/pankaj/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/pankaj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/pankaj/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/pankaj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/pankaj/anaconda3/include']
None


In [37]:
import numpy as np
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

In [52]:
import numpy as np
x = np.array([1, 2, 3, 4])
# print("Original array:")
# print(x)
# print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
# print("Original array:")
# print(x)
# print("Test if none of the elements of the said array is zero:")
print(np.all(x))


True
False


In [54]:
l=[[1,2,3],[1,2,4]]
np.all(np.array(l))

True

In [62]:
l=[[1,2,3],[1,2,0]]
np.all(np.array(l))

False

In [63]:
print(l)
a=np.array(l)
print(a)
if np.all(a):
    print('Zero is not  present  in the array ')
else:
    print('Zero is  present in the array')

[[1, 2, 3], [1, 2, 0]]
[[1 2 3]
 [1 2 0]]
Zero is  present in the array


In [70]:
l=[[0,0,0],[0,8,0]]
a=np.array(l)
print(a,np.any(a))

[[0 0 0]
 [0 8 0]] True


In [78]:
import numpy as np
l=[1,2,0,np.nan,np.inf]#nan ===> not a number , np.inf===> infinte 
print(np.isfinite(np.array(l)))

[ True  True  True False False]


In [79]:
l=[3,np.nan,np.inf]
print(np.isinf(np.array(l)))

[False False  True]


In [2]:
import numpy as np
l=[]
for i in range(int(input())):
    l.append(int(input()))
arr=np.array(l,float)
type(arr),arr[2]

3
2
3
4


(numpy.ndarray, 4.0)

In [21]:
import numpy as np
n,m=input().split()
n,m=int(n),int(m)
l,l1=[],[]
for i in range(n):
    l2=input().split()
    for k in l2:
        l1.append(int(k))
    l.append(l1)
    l2=[]
    l1=[]
arr=np.array(l)
transpose=np.transpose(arr)
flatten=arr.flatten()
print(transpose,flatten,sep='\n')


2 2
2 3
3 4
[[2 3]
 [3 4]]
[2 3 3 4]


### l=[]
l1=[1,2,3]
l.append(l1)
l.append(l1)
print(l)

In [16]:
n=input().split()
l1=[]
for i in n:
    l1.append(int(i))
    
print(l1)

1 2 3
[1, 2, 3]


In [4]:
# concatenate the  two arrays arrays at runtime
import numpy as np
n,m,p=input().split()
n,m,p=int(n),int(m),int(p)
l1,l2,l3=[],[],[]
for i in range(1,n+m+1):
    l=input().split()
    for j in l:
        l1.append(int(j))
    if i<=n:
        l2.append(l1)
    else:
        l3.append(l1)
    l1=[]
arr1=np.array(l2)
arr2=np.array(l3)
concatenate=np.concatenate((arr1,arr2),axis=0)
print(concatenate)

4 3 2
1 2
3 4
5 6
7 8
9 10
11 12
13 14
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [7]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
l=[[],[],[]]
arr=np.array(l)
x=np.zeros((3,3),dtype=np.float)
y=np.zeros((3,3),dtype=np.float)
z=np.zeros((3,3),dtype=np.float)
l=[x,y,z]
for i in range(3):
    arr[:i+1]=l[i]
print(arr)

ValueError: could not broadcast input array from shape (3,3) into shape (1,0)

In [11]:
np.ones((2,3))#default type is float

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
x=np.ones((2,3),int)
print(x*3)

[[3 3 3]
 [3 3 3]]


In [18]:
import numpy as np
zeros,ones,times=input().split()
zeros,ones,times=int(zeros),int(ones),int(times)


3 3 3


TypeError: _append_dispatcher() got an unexpected keyword argument 'axix'

In [ ]:
n,m=input().split()
for i in range(2*int(n)):
    l=input().split()
    for j in l:
        l1.append(int(j))
    l2.append(l1)
    l1=[]
print(l)