## The Iris Dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()#Object Creation
type(iris)#It returns the bunch object

sklearn.utils.Bunch

In [3]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [4]:
#Bunch object is like a dictionary
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
x=iris['data']
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y=iris['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
x_train=x[:100,:]
x_test=x[100:,:]
y_train=y[:100]
y_test=y[100:]

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier()
knc.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [9]:
from sklearn.metrics import accuracy_score
pred_train=knc.predict(x_train)
pred_test=knc.predict(x_test)
print('Training Score : ',accuracy_score(y_train,pred_train))
print('Testing Score : ',accuracy_score(y_test,pred_test))


Training Score :  1.0
Testing Score :  0.0


In [10]:
import pandas as pd
df=pd.DataFrame(x,columns=iris['feature_names'])
df['class']=y

In [11]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [12]:
#initial 50 ----> Setosa
#next    50 ----> Versicolor
#last    50 ----> Verginica

## RANDOM SAMPLING

In [13]:
from sklearn.model_selection import train_test_split#it gives the random sampling always whenever you will run it
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10])#by default it divides dataset into 75% and 25%
print(train,test)

[8, 4, 9, 10, 2, 3, 7] [6, 1, 5]


In [14]:
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10])
print(train,test)
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10],random_state=10)
print(train,test)#random_state fix the dataset splliting 

[8, 7, 4, 6, 5, 3, 2] [9, 10, 1]
[7, 4, 2, 1, 8, 5, 10] [9, 3, 6]


In [15]:
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10],random_state=10,train_size=8)
print(train,test)

[6, 7, 4, 2, 1, 8, 5, 10] [9, 3]


In [16]:
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10],random_state=10,test_size=8)
print(train,test)

[5, 10] [9, 3, 6, 7, 4, 2, 1, 8]


In [17]:
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10],random_state=10,train_size=5,test_size=2)
print(train,test)

[6, 7, 4, 2, 1] [9, 3]


In [18]:
train,test=train_test_split([1,2,3,4,5,6,7,8,9,10],random_state=10,train_size=.8)#we should use fraction approach for dividing the dataset
print(train,test)

[6, 7, 4, 2, 1, 8, 5, 10] [9, 3]


In [19]:
#2-D array/dataset
train,test=train_test_split([[1,2],[3,4],[5,6],[7,8],[9,10]],random_state=10)
print(train,test)

[[1, 2], [9, 10], [3, 4]] [[5, 6], [7, 8]]


In [20]:
train_x,test_x,train_y,test_y=train_test_split([[1,2],[3,4],[5,6],[7,8],[9,10]],[1,2,3,4,5],random_state=10)

In [21]:
print(train_x,test_x)
print(train_y,test_y)

[[1, 2], [9, 10], [3, 4]] [[5, 6], [7, 8]]
[1, 5, 2] [3, 4]


In [22]:
knc=KNeighborsClassifier()
knc.fit(x_train,y_train)
pred_train=knc.predict(x_train)
pred_test=knc.predict(x_test)
print('Training Score : ',accuracy_score(y_train,pred_train))
print('Training Score : ',accuracy_score(y_test,pred_test))

Training Score :  1.0
Training Score :  0.0


In [23]:
df=pd.read_csv('/home/pankaj/Downloads/classification/online_shop.csv')
df
df['Gender']=df['Gender'].map({'Female':0,'Male':1})

In [24]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)
print(len(x_train),len(y_train))

300 300


In [26]:
knc=KNeighborsClassifier()
knc.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [27]:
pred_train=knc.predict(x_train)
pred_test=knc.predict(x_test)
print('Training Score : ',accuracy_score(y_train,pred_train))
print('Training Score : ',accuracy_score(y_test,pred_test))


Training Score :  0.8766666666666667
Training Score :  0.88


# Fruits dataset

In [28]:
df=pd.read_csv('/home/pankaj/Downloads/classification/fruits.csv')
df

diameter  weight FruitName
0        3.0      30    Banana
1        6.0     100     Apple
2        6.1      95     Apple
3        3.2      35    Banana
4        5.5      80     Apple
5        7.1     120    Banana
6        2.5      60    Banana
7        2.3     100    Banana
8        4.8      70     Apple
9        4.8      79     Apple
10       5.8     120     Apple
11       2.6      85    Banana
12       6.0     110     Apple
13       6.3      95     Apple
14       3.0      40    Banana
15       3.5      25    Banana
16       5.5     100     Apple
17       7.5     120     Apple
18       2.5      50    Banana
19       2.7      40    Banana
20       4.8      90     Apple
21       5.8      90     Apple

In [29]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
print('Training Score : ',accuracy_score(y_train,pred_train))
print('Training Score : ',accuracy_score(y_test,pred_test))


Training Score :  0.8766666666666667
Training Score :  0.88


## Home Work

In [30]:
#Read KNeighbor classifier mathematics

# lecture-2nd,    12th July 2020

## How K-nearest Neighbors (KNN) works internally

In [31]:
#https://youtu.be/CLKW6uWJtTc      #Youtube link to understand the concept of KNN
#By default value of k is 5(k=5)

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [33]:
df=pd.read_csv('/home/pankaj/Downloads/classification/fruits.csv')
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)


In [34]:
knc=KNeighborsClassifier()
knc.fit(x_train,y_train)
pred_train=knc.predict(x_train)
pred_test=knc.predict(x_test)

In [35]:
print('Training Score',accuracy_score(y_train,pred_train))
print('Testing Score',accuracy_score(y_test,pred_test))


Training Score 0.9375
Testing Score 0.5


In [36]:
#A parameter  whick is passed in the constructor is Hyper parameter

# Feature Scaling

# 18th,July 2020

In [1]:
import numpy as np
a=np.array([[1,20],[2,15],[3,25],[2,20]])
a

array([[ 1, 20],
       [ 2, 15],
       [ 3, 25],
       [ 2, 20]])

In [6]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))
a1=sc.fit_transform(a)
a1

array([[0. , 0.5],
       [0.5, 0. ],
       [1. , 1. ],
       [0.5, 0.5]])

In [ ]:
a=np.array([[1,20],[2,15],[3,25],[2,20],[3,15]])
print('Before scaling')
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))
a1=sc.fit_transform(a)
